parameters:
    request_generator.options: []

services:
    request_generator:
        class:     Zeroem\CurlBundle\Curl\RequestGenerator
        arguments: [%request_generator.options%]

    remotehttpkernel:
        class:     Zeroem\CurlBundle\HttpKernel\RemoteHttpKernel
        arguments: [@?request_generator]